baseURL: https://gokarna-hugo.netlify.app
defaultContentLanguage: en
enableEmoji: yes
enableRobotsTXT: yes
languageCode: en
pygmentsStyle: monokai
theme: gokarna-hugo
title: Luke Klein
params:
  avatarAltText: Luke Klein
  avatarSize: size-xxl
  avatarURL: /images/luke-and-abby.png
  customHeadHTML: "    <!-- KaTeX -->\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css\"
    integrity=\"sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC\"
    crossorigin=\"anonymous\">\n    <script defer src=\"https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js\"
    integrity=\"sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja\"
    crossorigin=\"anonymous\"></script>\n    <script defer src=\"https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js\"
    integrity=\"sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR\"
    crossorigin=\"anonymous\"></script>\n    <script>\n      document.addEventListener(\"DOMContentLoaded\",
    function() {\n        renderMathInElement(document.body, {\n          // customised
    options\n          // • auto-render specific keys, e.g.:\n          delimiters:
    [\n            {left: '$$', right: '$$', display: true},\n            {left: '$',
    right: '$', display: false},\n          ],\n          // • rendering keys, e.g.:\n
    \         throwOnError : false\n        });\n      });\n    </script>\n  "
  description: Sky above, sand below and peace within
  footer: Luke Klein
  metaKeywords:
    - blog
    - gokarna
    - hugo
  showBackToTopButton: yes
  socialIcons:
    - name: twitter
      url: https://example.com
    - name: linkedin
      url: https://example.com
    - name: stackoverflow
      url: https://example.com
    - name: dribbble
      url: https://example.com
    - name: instagram
      url: https://example.com
    - name: twitch
      url: https://example.com
    - name: email
      url: mailto:example@example.com
menu:
  main:
    - name: Home
      pre: <span data-feather='home'></span>
      url: /
      weight: 1
    - name: Posts
      pre: <span data-feather='book'></span>
      url: /posts/
      weight: 2
    - name: Projects
      pre: <span data-feather='code'></span>
      url: /projects/
      weight: 3
    - name: Tags
      pre: <span data-feather='tag'></span>
      url: /tags/
      weight: 4
    - identifier: github
      pre: <span data-feather='github'></span>
      url: https://github.com/gokarna-theme/gokarna-hugo
      weight: 5
    - identifier: buymeacoffee
      pre: <span data-feather='coffee'></span>
      url: https://www.buymeacoffee.com/avijitgupta
      weight: 6
    - identifier: rss
      pre: <span data-feather='rss'></span>
      url: /index.xml
      weight: 7
markup:
  tableOfContents:
    endLevel: 4
    ordered: no
    startLevel: 1
minify:
  minifyOutput: yes
